"""init

Revision ID: cc955330c363
Revises: 
Create Date: 2026-06-16 21:46:20.715078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc955330c363'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('token_contract', sa.String(length=42), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('base_price_usdc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('k_value', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('token_contract'),
    sa.UniqueConstraint('wallet_address'),
    sa.UniqueConstraint('youtube_channel_id')
    )
    op.create_index(op.f('ix_creators_id'), 'creators', ['id'], unique=False)
    op.create_table('candles_5m',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume_tokens', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id', 'open_time', name='uix_creator_opentime')
    )
    op.create_index('idx_candles_creator_time', 'candles_5m', ['creator_id', 'open_time'], unique=False)
    op.create_index(op.f('ix_candles_5m_id'), 'candles_5m', ['id'], unique=False)
    op.create_table('price_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('price_usdc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('supply', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index('idx_price_events_creator_time', 'price_events', ['creator_id', 'block_timestamp'], unique=False)
    op.create_index(op.f('ix_price_events_id'), 'price_events', ['id'], unique=False)
    op.create_table('sentiment_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('modifier_bps', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('comment_sample', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_history_id'), 'sentiment_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_history_id'), table_name='sentiment_history')
    op.drop_table('sentiment_history')
    op.drop_index(op.f('ix_price_events_id'), table_name='price_events')
    op.drop_index('idx_price_events_creator_time', table_name='price_events')
    op.drop_table('price_events')
    op.drop_index(op.f('ix_candles_5m_id'), table_name='candles_5m')
    op.drop_index('idx_candles_creator_time', table_name='candles_5m')
    op.drop_table('candles_5m')
    op.drop_index(op.f('ix_creators_id'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
